# -*- coding: utf-8 -*-
"""knee joint simualtionV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABO2DLsC13PKxOkKDwtdBcborjD2Ce96
"""

# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  INTERACTIVE MULTI-MODAL BIOMECHANICAL DIGITAL TWIN  —  V2 FINAL           ║
# ║  Paste this ENTIRE file into ONE Google Colab cell and press Run            ║
# ║                                                                              ║
# ║  V1 OUTPUTS (unchanged, in order):                                          ║
# ║    VIZ 1   Gait motion  (angle / velocity / acceleration)                   ║
# ║    VIZ 2   Sensor simulation  Earth / Moon / Mars                           ║
# ║    VIZ 3   Noise injection on all sensor channels                           ║
# ║    VIZ 4   Kalman filter  true vs noisy vs estimated                        ║
# ║    VIZ 5   Feature extraction bar chart                                     ║
# ║    VIZ 6   Risk dashboard  (3 channels, risk-shaded)                        ║
# ║    VIZ 7   Knee anatomy snapshots across one gait cycle                     ║
# ║    VIZ 8   Gravity pressure profiles                                        ║
# ║    VIZ 9   Master 4×2 dashboard                                             ║
# ║    GIF 1   Live knee motion animation  (60 frames, 12 fps)                  ║
# ║    VIZ 10  Interactive slider (V1: angle + gravity)                         ║
# ║                                                                              ║
# ║  V2 OUTPUTS (new, appended below V1):                                       ║
# ║    VIZ 11  Foot tilt vs time                                                ║
# ║    VIZ 12  Full joint chain  ankle → knee → hip                             ║
# ║    VIZ 13  Force components  vertical vs lateral                            ║
# ║    VIZ 14  sEMG signal simulation                                           ║
# ║    VIZ 15  EMG vs force correlation                                         ║
# ║    VIZ 16  Sensor fusion output                                             ║
# ║    VIZ 17  V2 risk detection (foot tilt + EMG spikes + load peaks)          ║
# ║    VIZ 18  Clean vs noisy EMG comparison                                    ║
# ║    GIF 2   Full-chain animation  hip→knee→ankle + foot tilt                 ║
# ║    VIZ 19  V2 Interactive slider (foot tilt + weight + gravity)             ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

# ══════════════════════════════════════════════════════════════════════════════
#  SHARED IMPORTS  (used by both V1 and V2)
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import io, os
from PIL import Image as PILImage
from IPython.display import display, clear_output, Image as IPImage
import ipywidgets as widgets
import warnings
warnings.filterwarnings('ignore')
np.random.seed(42)

# ── INLINE DISPLAY HELPER ─────────────────────────────────────────────────────
def show(fig=None):
    """Save figure to buffer and display inline in Colab."""
    if fig is None:
        fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=130,
                bbox_inches='tight', facecolor=fig.get_facecolor())
    buf.seek(0)
    plt.close(fig)
    display(IPImage(data=buf.read()))

# ── COLOUR PALETTE ────────────────────────────────────────────────────────────
C = dict(
    true    ='#00D4AA', noisy  ='#FF6B6B', kalman ='#FFD93D',
    pressure='#74B9FF', vel    ='#A29BFE', high   ='#FF4757',
    medium  ='#FFA502', low    ='#2ED573', thigh  ='#74B9FF',
    calf    ='#00D4AA', earth  ='#00D4AA', moon   ='#FFD93D',
    mars    ='#FF6B6B', bg     ='#161B22', panel  ='#0D1117',
    # V2 additions
    ankle   ='#F8A5C2', knee2  ='#78E8FA', hip    ='#C3A6FF',
    emg     ='#FD9644', fusion ='#A29BFE', lateral='#FF6B81',
    tilt    ='#F8C291',
)

# ── GLOBAL PARAMETERS ─────────────────────────────────────────────────────────
GRAVITY     = {'Earth': 9.81, 'Moon': 1.62, 'Mars': 3.72}
MASS        = 70.0
NOISE_ANG   = 4.0
NOISE_VEL   = 3.0
NOISE_PRESS = 2.5
ANG_MAX     = 85.0
VEL_HIGH    = 72.0
VEL_MED     = 50.0

# ── AXES STYLING ──────────────────────────────────────────────────────────────
def _ax(ax, title, xl='', yl=''):
    ax.set_facecolor(C['bg'])
    ax.set_title(title, color='white', fontsize=10, fontweight='bold', pad=6)
    ax.set_xlabel(xl, color='#AAAAAA', fontsize=8)
    ax.set_ylabel(yl, color='#AAAAAA', fontsize=8)
    ax.tick_params(colors='#888', labelsize=7)
    for s in ax.spines.values():
        s.set_edgecolor('#30363D')
    ax.grid(color='#21262D', lw=0.5, ls='--', alpha=0.7)

def _leg(ax, **kw):
    ax.legend(fontsize=7, facecolor='#21262D',
              edgecolor='#444', labelcolor='white', **kw)

# ── KNEE GEOMETRY (V1) ────────────────────────────────────────────────────────
def knee_xy(deg):
    r = np.deg2rad(deg)
    return (0, 0), (0, -1), (np.sin(r), -1 - np.cos(r))

def draw_knee(ax, deg, calf_col=None):
    hip, knee, tip = knee_xy(deg)
    cc = calf_col or C['calf']
    ax.plot([hip[0], knee[0]], [hip[1], knee[1]],
            color=C['thigh'], lw=9, solid_capstyle='round', zorder=2)
    ax.plot([knee[0], tip[0]], [knee[1], tip[1]],
            color=cc, lw=9, solid_capstyle='round', alpha=.9, zorder=2)
    ax.scatter([hip[0], knee[0], tip[0]], [hip[1], knee[1], tip[1]],
               color='white', s=55, zorder=5)
    ax.axhline(-2.1, color='#444', lw=1.2, ls='--')
    ax.text(0, .32, f'{deg:.1f}°', ha='center',
            color='#FFD93D', fontsize=9, fontweight='bold')
    ax.set_xlim(-1.3, 1.3); ax.set_ylim(-2.4, .45)
    ax.set_aspect('equal'); ax.axis('off')
    ax.set_facecolor(C['bg'])

# ══════════════════════════════════════════════════════════════════════════════
#  V1 — PHASE FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def generate_gait(t_end=10.0, n=600):
    """
    Piecewise gait model — one cycle T = 1.1 s:
      Stance (φ < 0.60):  θ = 10° · sin(π·φ / 0.60)   — weight-bearing flex
      Swing  (φ ≥ 0.60):  θ = 65° · sin(π·(φ−0.60)/0.40) — swing-through arc
    """
    T  = 1.1
    t  = np.linspace(0, t_end, n)
    th = np.zeros(n)
    for i, ti in enumerate(t):
        phi = (ti % T) / T
        th[i] = (10.0 * np.sin(np.pi * phi / 0.60) if phi < 0.60
                 else 65.0 * np.sin(np.pi * (phi - 0.60) / 0.40))
    dt    = t[1] - t[0]
    th_d  = np.gradient(th,   dt)
    th_dd = np.gradient(th_d, dt)
    return t, th, th_d, th_dd

def simulate_sensors(th, th_d, g):
    vmax = max(np.abs(th_d).max(), 1e-6)
    lf   = np.abs(np.sin(np.deg2rad(th))) + 0.15 * np.abs(th_d) / vmax
    return {'angle': th, 'vel': th_d, 'pressure': MASS * g * lf / 100.0}

def all_envs(th, th_d):
    return {e: simulate_sensors(th, th_d, g) for e, g in GRAVITY.items()}

def add_noise(s):
    n = len(s['angle'])
    return {**s,
            'angle_n'    : s['angle']    + np.random.normal(0, NOISE_ANG,   n),
            'vel_n'      : s['vel']      + np.random.normal(0, NOISE_VEL,   n),
            'pressure_n' : s['pressure'] + np.random.normal(0, NOISE_PRESS, n)}

def kalman(z, Q=2.0, R=16.0):
    """1-D Kalman filter: fuses noisy sensor with model prediction."""
    x = np.zeros(len(z)); P = 1.0; x[0] = z[0]
    for i in range(1, len(z)):
        Pp = P + Q; K = Pp / (Pp + R)
        x[i] = x[i-1] + K * (z[i] - x[i-1]); P = (1 - K) * Pp
    return x

def classify_risk(th, th_d, pressure):
    p_mean, p_std = pressure.mean(), pressure.std()
    hi  = (np.abs(th) > ANG_MAX) | (np.abs(th_d) > VEL_HIGH)
    me  = (~hi) & ((np.abs(th_d) > VEL_MED) | (pressure > p_mean + 2*p_std))
    lvl = np.where(hi, 'HIGH', np.where(me, 'MEDIUM', 'LOW'))
    rc  = np.where(hi, C['high'], np.where(me, C['medium'], C['low']))
    n   = len(lvl)
    print(f"\n  {'Risk':<8} {'Count':>6}  {'%':>6}")
    print(f"  {'─'*24}")
    for r, sym in [('HIGH','⚠'), ('MEDIUM','△'), ('LOW','✓')]:
        c = (lvl == r).sum()
        print(f"  {sym} {r:<8} {c:>5}  {100*c/n:>5.1f}%")
    return lvl, hi, me, rc

# ── RUN V1 PHASES ─────────────────────────────────────────────────────────────
print("━"*65)
print("  ADAPTIVE BIOMECHANICAL KNEE DIGITAL TWIN  —  V1 PHASES")
print("━"*65)

t, th, th_d, th_dd = generate_gait()
envs   = all_envs(th, th_d)
s_e    = add_noise(envs['Earth'])
th_kal = kalman(s_e['angle_n'])
lvl, hi, me, rcol = classify_risk(th, th_d, s_e['pressure'])
T_c    = 1.1

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 1 — Gait Motion
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [VIZ 1] Gait-Based Motion …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 1 — PHASE 1: Gait-Based Knee Motion Model\n'
             'Blue band = Stance (60%)  |  Teal band = Swing (40%)',
             color='white', fontsize=12, fontweight='bold', y=.99)
rows = [(th,    C['true'],    'Angle [°]',     'Flexion Angle'),
        (th_d,  C['vel'],     'Velocity [°/s]','Angular Velocity'),
        (th_dd, C['pressure'],'Accel [°/s²]',  'Angular Acceleration')]
for ax, (arr, col, yl, title) in zip(axes, rows):
    ax.plot(t, arr, color=col, lw=1.6)
    ax.axhline(0, color='#444', lw=.8, ls=':')
    _ax(ax, title, yl=yl)
    for cyc in range(int(t[-1]/T_c) + 2):
        ax.axvspan(cyc*T_c,          cyc*T_c + .6*T_c, alpha=.06, color='#74B9FF')
        ax.axvspan(cyc*T_c + .6*T_c, (cyc+1)*T_c,      alpha=.06, color='#00D4AA')
axes[-1].set_xlabel('Time [s]', color='#AAAAAA', fontsize=8)
p1 = mpatches.Patch(color='#74B9FF', alpha=.4, label='Stance 60%')
p2 = mpatches.Patch(color='#00D4AA', alpha=.4, label='Swing  40%')
axes[0].legend(handles=[p1, p2], fontsize=8,
               facecolor='#21262D', edgecolor='#444', labelcolor='white')
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 2 — Sensors + Gravity
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 2] Multi-Sensor & Gravity …")
fig, axes = plt.subplots(2, 3, figsize=(16, 8))
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 2 — PHASES 2 & 3: Multi-Sensor Simulation Across Gravity\n'
             'pressure = mass × g × load_factor(θ, θ̇)',
             color='white', fontsize=12, fontweight='bold')
for ci, (env, col) in enumerate(zip(['Earth','Moon','Mars'],
                                     [C['earth'],C['moon'],C['mars']])):
    s = envs[env]; g = GRAVITY[env]
    ax0 = axes[0, ci]
    ax0.plot(t, s['angle'], color=col, lw=1.5)
    ax0.fill_between(t, s['angle'], alpha=.08, color=col)
    _ax(ax0, f'{env}  g={g} m/s²', yl='Angle [°]' if ci==0 else '')
    ax0.set_ylim(-5, 80)
    ax0.text(.98,.95,f"max={s['angle'].max():.1f}°",transform=ax0.transAxes,
             ha='right',va='top',color=col,fontsize=8,fontweight='bold')
    ax1 = axes[1, ci]
    ax1.plot(t, s['pressure'], color=col, lw=1.5, alpha=.9)
    ax1.fill_between(t, s['pressure'], alpha=.10, color=col)
    _ax(ax1, f'Pressure — {env}', xl='Time [s]',
        yl='Pressure [N/cm²]' if ci==0 else '')
    ax1.text(.98,.95,f"max={s['pressure'].max():.3f} N/cm²",
             transform=ax1.transAxes,ha='right',va='top',
             color=col,fontsize=8,fontweight='bold')
plt.tight_layout(); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 3 — Noise Injection
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 3] Noise Injection …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 3 — PHASE 4: Gaussian Noise on IMU & Pressure Sensors\n'
             'Noisy (coral) vs Clean (teal)',
             color='white', fontsize=12, fontweight='bold', y=.99)
pairs = [('angle',   'angle_n',   'Angle [°]',    'IMU Angle'),
         ('vel',     'vel_n',     'Velocity [°/s]','IMU Angular Velocity'),
         ('pressure','pressure_n','N/cm²',          'Pressure Sensor')]
for ax, (tk, nk, yl, title) in zip(axes, pairs):
    tr = s_e[tk]; nr = s_e[nk]
    snr = 10 * np.log10(np.var(tr) / (np.var(nr - tr) + 1e-9))
    ax.plot(t, nr, color=C['noisy'], lw=.9, alpha=.65, label='Noisy (sensor)')
    ax.plot(t, tr, color=C['true'],  lw=1.8,            label='True  (clean)')
    _ax(ax, title, yl=yl)
    ax.text(.99,.95,f'SNR={snr:.1f} dB',transform=ax.transAxes,
            ha='right',va='top',color='#AAAAAA',fontsize=8)
    _leg(ax, loc='upper left')
axes[-1].set_xlabel('Time [s]', color='#AAAAAA', fontsize=8)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 4 — Kalman Filter
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 4] Kalman Filter …")
rn = np.sqrt(np.mean((s_e['angle_n'] - th)**2))
rk = np.sqrt(np.mean((th_kal        - th)**2))
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 8), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle(f'VIZ 4 — PHASE 5: Kalman Filter State Estimation\n'
             f'RMSE  Noisy={rn:.2f}°  →  Kalman={rk:.2f}°  '
             f'({100*(1-rk/rn):.1f}% improvement)',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax1.plot(t, s_e['angle_n'], color=C['noisy'],  lw=.8, alpha=.55,
         label=f'Noisy IMU  RMSE={rn:.2f}°')
ax1.plot(t, th,             color=C['true'],   lw=2.2, label='True angle')
ax1.plot(t, th_kal,         color=C['kalman'], lw=1.8, ls='--',
         label=f'Kalman est  RMSE={rk:.2f}°')
_ax(ax1,'True vs Noisy vs Kalman',yl='Angle [°]'); _leg(ax1)
res_n = s_e['angle_n'] - th; res_k = th_kal - th
ax2.plot(t, res_n, color=C['noisy'],  lw=.9, alpha=.6,  label=f'Noisy  σ={res_n.std():.2f}°')
ax2.plot(t, res_k, color=C['kalman'], lw=1.4,            label=f'Kalman σ={res_k.std():.2f}°')
ax2.axhline(0, color='white', lw=.7, ls=':')
ax2.fill_between(t, 2*NOISE_ANG, -2*NOISE_ANG, alpha=.05, color='white', label='±2σ band')
_ax(ax2,'Residual Error',xl='Time [s]',yl='Error [°]'); _leg(ax2)
plt.tight_layout(rect=[0, 0, 1, .95]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 5 — Feature Extraction
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 5] Feature Extraction …")
env_names = ['Earth','Moon','Mars']
env_cols  = [C['earth'],C['moon'],C['mars']]
feats = {}
for env in env_names:
    se = add_noise(envs[env])
    zc  = np.where(np.diff(np.sign(se['vel'])))[0]
    cad = (len(zc)/2)/(t[-1]-t[0])*60
    feats[env] = {
        'Peak Pressure\n[N/cm²]'  : se['pressure'].max(),
        'Peak Velocity\n[°/s]'    : np.abs(se['vel']).max(),
        'Range of Motion\n[°]'    : se['angle'].max()-se['angle'].min(),
        'Load Asymmetry\n[index]' : se['pressure'].std()/(se['pressure'].mean()+1e-6),
        'Cadence\n[steps/min]'    : cad,
    }
metrics = list(feats['Earth'].keys())
fig, axes = plt.subplots(1, len(metrics), figsize=(18, 5))
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 5 — PHASE 6: Biomechanical Feature Extraction by Environment',
             color='white', fontsize=12, fontweight='bold')
for ax, met in zip(axes, metrics):
    vals = [feats[e][met] for e in env_names]
    bars = ax.bar(env_names, vals, color=env_cols, width=.5,
                  edgecolor='#30363D', lw=.5)
    for b, v in zip(bars, vals):
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+.01*max(vals),
                f'{v:.2f}', ha='center', color='white', fontsize=8, fontweight='bold')
    _ax(ax, met.replace('\n',' '))
    ax.tick_params(axis='x', colors='#AAAAAA', labelsize=8)
plt.tight_layout(); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 6 — Risk Dashboard
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 6] Risk Dashboard …")
fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 6 — PHASE 7: Risk & Anomaly Detection Dashboard\n'
             'RED = High  |  ORANGE = Medium  |  GREEN = Low',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax = axes[0]
ax.plot(t, th, color=C['true'], lw=1.5, zorder=3)
ax.fill_between(t, th, where=hi, color=C['high'],   alpha=.35, label='HIGH risk')
ax.fill_between(t, th, where=me, color=C['medium'], alpha=.30, label='MEDIUM risk')
ax.axhline(ANG_MAX, color=C['high'], lw=1.0, ls='--', label=f'Limit {ANG_MAX}°')
_ax(ax,'Knee Angle — Risk Zones',yl='Angle [°]'); _leg(ax)
ax = axes[1]
ax.plot(t, th_d, color=C['vel'], lw=1.4, zorder=3)
for val, col, lbl in [(VEL_HIGH,C['high'],f'HIGH ±{VEL_HIGH}°/s'),
                       (VEL_MED, C['medium'],f'MED ±{VEL_MED}°/s')]:
    ax.axhline( val, color=col, lw=1.0, ls='--', label=lbl)
    ax.axhline(-val, color=col, lw=1.0, ls='--')
ax.fill_between(t,th_d, VEL_HIGH,where=(th_d> VEL_HIGH),color=C['high'],alpha=.3)
ax.fill_between(t,th_d,-VEL_HIGH,where=(th_d<-VEL_HIGH),color=C['high'],alpha=.3)
_ax(ax,'Angular Velocity — Thresholds',yl='Velocity [°/s]'); _leg(ax)
ax = axes[2]
ax.scatter(t, s_e['pressure'], c=rcol, s=4, linewidths=0, zorder=3)
ax.plot(t, s_e['pressure'], color='white', lw=.4, alpha=.2)
for lbl, col in [('HIGH',C['high']),('MEDIUM',C['medium']),('LOW',C['low'])]:
    ax.scatter([],[],color=col,s=20,label=lbl)
_ax(ax,'Joint Pressure — Risk Classification',xl='Time [s]',yl='N/cm²'); _leg(ax)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 7 — Knee Anatomy Snapshots
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 7] Knee Anatomy Snapshots …")
n_snap  = 10
t_snaps = np.linspace(0, T_c, n_snap, endpoint=False)
idxs    = [np.argmin(np.abs(t - ts)) for ts in t_snaps]
fig = plt.figure(figsize=(20, 5))
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 7 — PHASE 8: Knee Anatomy Snapshots Across One Gait Cycle\n'
             'Calf colour = risk  |  angle & pressure shown per frame',
             color='white', fontsize=11, fontweight='bold')
for fi, di in enumerate(idxs):
    ax = fig.add_subplot(1, n_snap, fi + 1)
    r  = lvl[di]
    cc = C['high'] if r=='HIGH' else C['medium'] if r=='MEDIUM' else C['low']
    draw_knee(ax, th[di], calf_col=cc)
    pv = s_e['pressure'][di]
    ax.text(0,-2.22,f'{pv:.2f}',  ha='center',color=C['pressure'],fontsize=7)
    ax.text(0,-2.36,'N/cm²',      ha='center',color=C['pressure'],fontsize=6,alpha=.7)
    ax.text(0,-1.88, r,           ha='center',color=cc,fontsize=7,fontweight='bold')
    ax.set_title(f't={t[di]:.2f}s',color='#888',fontsize=7,pad=2)
plt.tight_layout(rect=[0, 0, 1, .90]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 8 — Gravity Pressure Profiles
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 8] Gravity Pressure Profiles …")
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 8 — PHASE 8: Pressure Profile Comparison Across Environments',
             color='white', fontsize=12, fontweight='bold')
for ax, env, col in zip(axes,['Earth','Moon','Mars'],
                          [C['earth'],C['moon'],C['mars']]):
    s = envs[env]
    ax.plot(t, s['pressure'], color=col, lw=1.5, alpha=.9)
    ax.fill_between(t, s['pressure'], alpha=.12, color=col)
    ax.axhline(s['pressure'].mean(), color='white', lw=.8, ls='--',
               label=f"mean={s['pressure'].mean():.3f}")
    _ax(ax, f'{env}  (g={GRAVITY[env]} m/s²)', xl='Time [s]',
        yl='Pressure [N/cm²]' if env=='Earth' else '')
    _leg(ax)
plt.tight_layout(); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 9 — Master 4×2 Dashboard
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 9] Master Dashboard …")
fig = plt.figure(figsize=(18, 16))
fig.patch.set_facecolor(C['panel'])
gs  = gridspec.GridSpec(4, 2, figure=fig, hspace=.46, wspace=.32)
fig.suptitle('VIZ 9 — MASTER DASHBOARD: Adaptive Knee Digital Twin\n'
             'Space Environments  |  All V1 Phases Integrated',
             color='white', fontsize=13, fontweight='bold', y=.99)

ax  = fig.add_subplot(gs[0,0]); ax2 = ax.twinx()
ax.plot(t, th,   color=C['true'], lw=1.8, label='Angle [°]')
ax2.plot(t, th_d, color=C['vel'], lw=1.2, alpha=.7, ls='--', label='Vel [°/s]')
_ax(ax,'Angle & Velocity',yl='Angle [°]')
ax2.tick_params(colors='#888',labelsize=7)
ax2.set_ylabel('Vel [°/s]',color='#AAAAAA',fontsize=8)
ax2.spines['right'].set_edgecolor('#30363D')
h1,l1=ax.get_legend_handles_labels(); h2,l2=ax2.get_legend_handles_labels()
ax.legend(h1+h2,l1+l2,fontsize=7,facecolor='#21262D',edgecolor='#444',labelcolor='white')

ax = fig.add_subplot(gs[0,1])
ax.plot(t,s_e['angle_n'],color=C['noisy'],lw=.8,alpha=.55,label='Noisy')
ax.plot(t,th,            color=C['true'], lw=2.2,          label='True')
ax.plot(t,th_kal,        color=C['kalman'],lw=1.8,ls='--', label='Kalman')
_ax(ax,'Kalman Filter',yl='Angle [°]'); _leg(ax)

ax = fig.add_subplot(gs[1,0])
for env, col in zip(['Earth','Moon','Mars'],[C['earth'],C['moon'],C['mars']]):
    ax.plot(t,envs[env]['pressure'],color=col,lw=1.4,alpha=.85,
            label=f'{env} g={GRAVITY[env]}')
_ax(ax,'Joint Pressure — All Environments',yl='N/cm²'); _leg(ax)

ax = fig.add_subplot(gs[1,1])
ax.scatter(t,np.abs(th),c=rcol,s=3,linewidths=0,zorder=3)
ax.axhline(ANG_MAX,color=C['high'],lw=1.0,ls='--',label=f'Limit {ANG_MAX}°')
for lbl,col in [('HIGH',C['high']),('MEDIUM',C['medium']),('LOW',C['low'])]:
    ax.scatter([],[],color=col,s=20,label=lbl)
_ax(ax,'Risk Classification',yl='|Angle| [°]'); _leg(ax,loc='upper right')

ax = fig.add_subplot(gs[2,0])
ax.plot(t,th_d,color=C['vel'],lw=1.4)
ax.axhline( VEL_HIGH,color=C['high'],  lw=.9,ls='--',label=f'HIGH ±{VEL_HIGH}')
ax.axhline(-VEL_HIGH,color=C['high'],  lw=.9,ls='--')
ax.axhline( VEL_MED, color=C['medium'],lw=.8,ls=':',label=f'MED ±{VEL_MED}')
ax.axhline(-VEL_MED, color=C['medium'],lw=.8,ls=':')
ax.fill_between(t,th_d, VEL_HIGH,where=(th_d> VEL_HIGH),color=C['high'],alpha=.3)
ax.fill_between(t,th_d,-VEL_HIGH,where=(th_d<-VEL_HIGH),color=C['high'],alpha=.3)
_ax(ax,'Velocity + Anomaly Zones',yl='Vel [°/s]'); _leg(ax)

ax = fig.add_subplot(gs[2,1])
rn2=s_e['angle_n']-th; rk2=th_kal-th
ax.plot(t,rn2,color=C['noisy'], lw=.8,alpha=.6, label=f'Noisy  σ={rn2.std():.2f}°')
ax.plot(t,rk2,color=C['kalman'],lw=1.4,          label=f'Kalman σ={rk2.std():.2f}°')
ax.axhline(0,color='white',lw=.7,ls=':')
_ax(ax,'Residual Error Analysis',yl='Error [°]'); _leg(ax)

ax = fig.add_subplot(gs[3,0])
pvals=[envs[e]['pressure'].max() for e in ['Earth','Moon','Mars']]
bars=ax.bar(['Earth','Moon','Mars'],pvals,
            color=[C['earth'],C['moon'],C['mars']],
            width=.5,edgecolor='#30363D',lw=.5)
for b,v in zip(bars,pvals):
    ax.text(b.get_x()+b.get_width()/2,b.get_height()+.001*max(pvals),
            f'{v:.3f}',ha='center',color='white',fontsize=9,fontweight='bold')
ax.tick_params(axis='x',colors='#AAAAAA',labelsize=9)
_ax(ax,'Peak Pressure by Environment',yl='N/cm²')

ax = fig.add_subplot(gs[3,1])
n_tot=len(lvl)
counts=[(lvl=='HIGH').sum(),(lvl=='MEDIUM').sum(),(lvl=='LOW').sum()]
labels=[f'High\n{100*counts[0]/n_tot:.1f}%',
        f'Medium\n{100*counts[1]/n_tot:.1f}%',
        f'Low\n{100*counts[2]/n_tot:.1f}%']
wedges,_=ax.pie(counts,colors=[C['high'],C['medium'],C['low']],
                startangle=90,wedgeprops=dict(lw=.5,edgecolor='#30363D'))
ax.legend(wedges,labels,fontsize=8,loc='center left',bbox_to_anchor=(.80,.5),
          facecolor='#21262D',edgecolor='#444',labelcolor='white')
ax.set_facecolor(C['bg'])
ax.set_title('Risk Distribution',color='white',fontsize=10,fontweight='bold',pad=7)
show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  GIF 1 — Live Knee Motion Animation
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [GIF 1] Rendering knee motion animation (60 frames) …")
frame_indices = np.linspace(0, int(2*T_c/(t[1]-t[0])), 60, dtype=int)
frame_indices = np.clip(frame_indices, 0, len(t)-1)
pil_frames = []

for fi, di in enumerate(frame_indices):
    fig = plt.figure(figsize=(13, 5))
    fig.patch.set_facecolor(C['panel'])
    ax_body = fig.add_axes([0.02, 0.05, 0.28, 0.88])
    ax_body.set_facecolor(C['bg'])
    ax_body.set_xlim(-1.3,1.3); ax_body.set_ylim(-2.5,0.55)
    ax_body.set_aspect('equal'); ax_body.axis('off')
    ang = th[di]; r = np.deg2rad(ang)
    hip=(0,0); knee=(0,-1); tip=(np.sin(r),-1-np.cos(r))
    rc_now = C['high'] if hi[di] else C['medium'] if me[di] else C['low']
    rlvl   = 'HIGH'   if hi[di] else 'MEDIUM'    if me[di] else 'LOW'
    ax_body.plot([hip[0],knee[0]],[hip[1],knee[1]],
                 color=C['thigh'],lw=12,solid_capstyle='round',zorder=2)
    ax_body.plot([knee[0],tip[0]],[knee[1],tip[1]],
                 color=rc_now,lw=12,solid_capstyle='round',alpha=.9,zorder=2)
    ax_body.scatter([hip[0],knee[0],tip[0]],[hip[1],knee[1],tip[1]],
                    color='white',s=100,zorder=5)
    ax_body.axhline(-2.15,color='#444',lw=1.5,ls='--')
    ax_body.text(0, 0.42,f'θ = {ang:.1f}°',ha='center',
                 color='#FFD93D',fontsize=14,fontweight='bold')
    ax_body.text(0,-2.28,f'P = {s_e["pressure"][di]:.2f} N/cm²',
                 ha='center',color=C['pressure'],fontsize=10)
    ax_body.text(0,-2.45,f'Risk: {rlvl}',ha='center',
                 color=rc_now,fontsize=10,fontweight='bold')
    phi_now = (t[di] % T_c)/T_c
    ax_body.text(0,0.24,'STANCE' if phi_now<0.6 else 'SWING',
                 ha='center',color='#74B9FF' if phi_now<0.6 else C['true'],
                 fontsize=9,alpha=.85)
    ax_body.set_title('Knee Animation',color='white',fontsize=11,
                      fontweight='bold',pad=4)
    x_lim = t[int(2*T_c/(t[1]-t[0]))]
    ax_ang = fig.add_axes([0.34,0.55,0.62,0.37])
    ax_ang.set_facecolor(C['bg'])
    ax_ang.plot(t[:di+1],th[:di+1],color=C['true'],lw=1.8)
    ax_ang.axvline(t[di],color='white',lw=.8,alpha=.5)
    ax_ang.scatter([t[di]],[th[di]],color='#FFD93D',s=55,zorder=5)
    ax_ang.set_xlim(0,x_lim); ax_ang.set_ylim(-5,78)
    ax_ang.set_ylabel('Angle [°]',color='#AAAAAA',fontsize=8)
    ax_ang.tick_params(colors='#888',labelsize=7)
    for s in ax_ang.spines.values(): s.set_edgecolor('#30363D')
    ax_ang.grid(color='#21262D',lw=.5,ls='--',alpha=.7)
    ax_ang.set_title('Real-time Angle',color='white',fontsize=9,
                     fontweight='bold',pad=4)
    ax_pv  = fig.add_axes([0.34,0.08,0.62,0.37])
    ax_pv2 = ax_pv.twinx()
    ax_pv.set_facecolor(C['bg'])
    ax_pv.plot(t[:di+1],s_e['pressure'][:di+1],
               color=C['pressure'],lw=1.5,label='Pressure [N/cm²]')
    ax_pv2.plot(t[:di+1],th_d[:di+1],
                color=C['vel'],lw=1.0,alpha=.7,label='Velocity [°/s]')
    ax_pv.axvline(t[di],color='white',lw=.8,alpha=.5)
    ax_pv.scatter([t[di]],[s_e['pressure'][di]],
                  color=C['pressure'],s=50,zorder=5)
    ax_pv.set_xlim(0,x_lim)
    ax_pv.set_xlabel('Time [s]',color='#AAAAAA',fontsize=8)
    ax_pv.set_ylabel('Pressure [N/cm²]',color='#AAAAAA',fontsize=8)
    ax_pv2.set_ylabel('Velocity [°/s]',color='#AAAAAA',fontsize=8)
    for ax_ in [ax_pv,ax_pv2]:
        ax_.tick_params(colors='#888',labelsize=7)
        for s in ax_.spines.values(): s.set_edgecolor('#30363D')
    ax_pv.grid(color='#21262D',lw=.5,ls='--',alpha=.7)
    h1,l1=ax_pv.get_legend_handles_labels()
    h2,l2=ax_pv2.get_legend_handles_labels()
    ax_pv.legend(h1+h2,l1+l2,fontsize=7,facecolor='#21262D',
                 edgecolor='#444',labelcolor='white',loc='upper left')
    ax_pv.set_title('Pressure & Velocity',color='white',
                    fontsize=9,fontweight='bold',pad=4)
    fig.text(.5,.98,
             'Adaptive Knee Digital Twin  |  Earth g=9.81 m/s²  |  '
             'Calf colour = Risk level',
             ha='center',va='top',color='white',fontsize=10,fontweight='bold')
    buf=io.BytesIO()
    fig.savefig(buf,format='png',dpi=100,bbox_inches='tight',
                facecolor=fig.get_facecolor())
    buf.seek(0)
    pil_frames.append(PILImage.open(buf).copy().convert('RGB'))
    plt.close(fig)
    if (fi+1)%15==0:
        print(f"    {fi+1}/{len(frame_indices)} frames")

gif1 = 'knee_motion_animation.gif'
pil_frames[0].save(gif1,save_all=True,append_images=pil_frames[1:],
                   duration=80,loop=0,optimize=False)
print(f"  ✓ GIF 1 saved → {gif1}  ({os.path.getsize(gif1)/1e6:.1f} MB)")
display(IPImage(filename=gif1))

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 10 — V1 Interactive Slider
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [VIZ 10] V1 Interactive Slider …\n")

def _v1_update(angle=45, environment='Earth'):
    g  = GRAVITY[environment]; tr = np.deg2rad(angle)
    pv = MASS*g*(abs(np.sin(tr))+0.05)/100.0
    risk = ('HIGH' if angle>ANG_MAX else 'MEDIUM' if angle>ANG_MAX*0.7 else 'LOW')
    rc   = C['high'] if risk=='HIGH' else C['medium'] if risk=='MEDIUM' else C['low']
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.patch.set_facecolor(C['panel'])
    fig.suptitle(f'VIZ 10 — V1 Interactive  |  θ={angle}°  |  {environment} (g={g} m/s²)',
                 color='white',fontsize=12,fontweight='bold')
    draw_knee(axes[0],angle,calf_col=rc)
    axes[0].text(0,-2.22,f'P = {pv:.2f} N/cm²',ha='center',
                 color=C['pressure'],fontsize=10)
    axes[0].text(0,-2.40,f'Risk: {risk}',ha='center',
                 color=rc,fontsize=10,fontweight='bold')
    axes[0].set_title('Live Anatomy',color='white',fontsize=10,
                      fontweight='bold',pad=5)
    ax2=axes[1]; ax2.set_facecolor(C['bg'])
    score=3 if risk=='HIGH' else 2 if risk=='MEDIUM' else 1
    cats=['Angle [°]','Pressure×10\n[N/cm²]','Risk Score']
    vals2=[angle,pv*10,score*30]; bcols=['#FFD93D',C['pressure'],rc]
    bs=ax2.barh(cats,vals2,color=bcols,height=.4,edgecolor='#30363D',lw=.5)
    ax2.set_xlim(0,110)
    for b,raw in zip(bs,[f'{angle}°',f'{pv:.2f} N/cm²',f'{risk}']):
        ax2.text(b.get_width()+1,b.get_y()+b.get_height()/2,
                 raw,va='center',color='white',fontsize=9,fontweight='bold')
    _ax(ax2,'Sensor Readout')
    ax3=axes[2]; ax3.set_facecolor(C['bg'])
    envl=['Earth','Moon','Mars']
    pall=[MASS*GRAVITY[e]*(abs(np.sin(tr))+0.05)/100.0 for e in envl]
    bb=ax3.bar(envl,pall,color=[C['earth'],C['moon'],C['mars']],
               width=.5,edgecolor='#30363D',lw=.5)
    for b,v in zip(bb,pall):
        ax3.text(b.get_x()+b.get_width()/2,b.get_height()+.001*max(pall),
                 f'{v:.3f}',ha='center',color='white',fontsize=9,fontweight='bold')
    bb[envl.index(environment)].set_edgecolor('white')
    bb[envl.index(environment)].set_linewidth(2.5)
    _ax(ax3,f'Pressure at θ={angle}°',yl='N/cm²')
    ax3.tick_params(axis='x',colors='#AAAAAA',labelsize=9)
    plt.tight_layout(rect=[0,0,1,.91]); show(fig)

aw1=widgets.IntSlider(value=45,min=0,max=90,step=1,description='Angle °:',
                      style={'description_width':'70px'},
                      layout=widgets.Layout(width='380px'))
ew1=widgets.Dropdown(options=['Earth','Moon','Mars'],value='Earth',
                     description='Gravity:',style={'description_width':'70px'},
                     layout=widgets.Layout(width='200px'))
display(widgets.HBox([aw1,ew1]),
        widgets.interactive_output(_v1_update,{'angle':aw1,'environment':ew1}))

# ══════════════════════════════════════════════════════════════════════════════
# ██████████████████████████████████████████████████████████████████████████
#  V2 EXTENSION — BEGINS HERE
#  All V1 code above is UNCHANGED.  Everything below is purely additive.
# ██████████████████████████████████████████████████████████████████████████
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "━"*65)
print("  V2 EXTENSION — MULTI-MODAL BIOMECHANICAL DIGITAL TWIN")
print("━"*65)

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PARAMETERS
# ══════════════════════════════════════════════════════════════════════════════
FOOT_TILT_AMP  = 15.0   # degrees — peak inversion/eversion amplitude
FOOT_TILT_MAX  = 25.0   # HIGH-risk tilt limit [°]
FOOT_TILT_MED  = 15.0   # MEDIUM-risk tilt limit [°]
EMG_NOISE_STD  = 0.05   # wireless artefact noise
# Joint coupling coefficients
A1, A2 = 0.5, 0.3      # θ_knee  = A1·θ_ankle + A2·θ_foot_tilt
B1     = 0.6            # θ_hip   = B1·θ_knee
# Sensor fusion weights  (sum to 1)
W1, W2, W3 = 0.4, 0.35, 0.25  # angle, velocity, EMG

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE A — FOOT TILT MODEL
#  θ_foot_tilt(t) = FOOT_TILT_AMP · sin(2π·t/T_tilt + π/4)
#  Negative = inversion (inward), Positive = eversion (outward)
# ══════════════════════════════════════════════════════════════════════════════
T_tilt     = 2.5                                  # tilt oscillation period [s]
foot_tilt  = FOOT_TILT_AMP * np.sin(2*np.pi*t/T_tilt + np.pi/4)

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE B — FULL JOINT CHAIN  ankle → knee → hip
#  Each joint has a phase-shifted sinusoidal component plus tilt coupling.
# ══════════════════════════════════════════════════════════════════════════════
dt = t[1] - t[0]

# Ankle: base gait + foot tilt effect (tilt shifts ankle angle)
th_ankle     = 20*np.sin(2*np.pi*t/T_c)  + 0.4*foot_tilt
th_ankle_d   = np.gradient(th_ankle,  dt)
th_ankle_dd  = np.gradient(th_ankle_d,dt)

# Knee: coupled to ankle + tilt (V2 knee is a re-derived signal)
th_knee_v2   = A1*th_ankle + A2*foot_tilt
th_knee_v2_d = np.gradient(th_knee_v2, dt)

# Hip: coupled to knee, phase-shifted
th_hip       = B1*th_knee_v2 + 5*np.sin(2*np.pi*t/T_c + np.pi/6)
th_hip_d     = np.gradient(th_hip, dt)

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE C — FORCE VECTOR MODEL  (with Earth gravity default)
#  F_eff     = m·g·cos(θ_foot_tilt)   — vertical effective load
#  F_lateral = m·g·sin(θ_foot_tilt)   — lateral destabilising force
#  F_joint   = √(F_eff² + F_lateral²) · |sin(θ_knee)| — total joint load
# ══════════════════════════════════════════════════════════════════════════════
g_now       = GRAVITY['Earth']
ft_rad      = np.deg2rad(foot_tilt)
F_eff       = MASS * g_now * np.cos(ft_rad)
F_lateral   = MASS * g_now * np.sin(ft_rad)
F_total     = np.sqrt(F_eff**2 + F_lateral**2) * np.abs(np.sin(np.deg2rad(th_knee_v2)))

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE D — sEMG SIGNAL SIMULATION
#  EMG ∝ joint load × angular velocity (activation bursts at motion peaks)
#  Base: band-limited burst noise.  Added: wireless Gaussian artefact.
# ══════════════════════════════════════════════════════════════════════════════
# Normalised activation driver (0–1)
vel_norm    = np.abs(th_knee_v2_d) / (np.abs(th_knee_v2_d).max() + 1e-6)
load_norm   = F_total               / (F_total.max()              + 1e-6)
activation  = 0.6*vel_norm + 0.4*load_norm          # weighted blend

# Burst noise shaped by activation envelope
burst_noise = activation * np.random.normal(0, 1, len(t))
# Smooth with a short running-average to approximate band-limited nature
from numpy.lib.stride_tricks import sliding_window_view
def smooth(x, w=15):
    """Simple moving-average smoothing."""
    pad = np.pad(x, w//2, mode='edge')
    return np.convolve(pad, np.ones(w)/w, mode='valid')[:len(x)]

emg_clean   = smooth(np.abs(burst_noise), w=7)  # rectified + smoothed envelope
emg_noisy   = emg_clean + np.random.normal(0, EMG_NOISE_STD, len(t))
emg_noisy   = np.clip(emg_noisy, 0, None)

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE E — SENSOR FUSION
#  joint_load_estimate = W1·|angle_norm| + W2·|vel_norm| + W3·emg_norm
# ══════════════════════════════════════════════════════════════════════════════
ang_norm_v2  = np.abs(th_knee_v2) / (np.abs(th_knee_v2).max() + 1e-6)
vel_norm_v2  = np.abs(th_knee_v2_d) / (np.abs(th_knee_v2_d).max() + 1e-6)
emg_norm     = emg_clean / (emg_clean.max() + 1e-6)
fusion_est   = W1*ang_norm_v2 + W2*vel_norm_v2 + W3*emg_norm

# ══════════════════════════════════════════════════════════════════════════════
#  V2 PHASE F — V2 RISK CLASSIFICATION
#  Checks: foot tilt excess + EMG spike + load peak + velocity
# ══════════════════════════════════════════════════════════════════════════════
emg_spike_thr = emg_clean.mean() + 2.5*emg_clean.std()
load_thr      = F_total.mean()   + 2.0*F_total.std()
hi_v2 = ((np.abs(foot_tilt) > FOOT_TILT_MAX) |
          (np.abs(th_knee_v2_d) > VEL_HIGH)  |
          (F_total > load_thr))
me_v2 = (~hi_v2) & ((np.abs(foot_tilt) > FOOT_TILT_MED) |
                      (emg_clean > emg_spike_thr))
lvl_v2 = np.where(hi_v2,'HIGH',np.where(me_v2,'MEDIUM','LOW'))
rc_v2  = np.where(hi_v2,C['high'],np.where(me_v2,C['medium'],C['low']))
n2 = len(lvl_v2)
print(f"\n  V2 Risk Summary:")
for r,sym in [('HIGH','⚠'),('MEDIUM','△'),('LOW','✓')]:
    c=(lvl_v2==r).sum()
    print(f"    {sym} {r:<8} {c:>5}  {100*c/n2:>5.1f}%")

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 11 — Foot Tilt vs Time
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [VIZ 11] Foot Tilt vs Time …")
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 7), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 11 — V2: Foot Tilt Model\n'
             'Negative = Inversion (inward)  |  Positive = Eversion (outward)',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax1.plot(t, foot_tilt, color=C['tilt'], lw=1.8)
ax1.fill_between(t, foot_tilt, where=(foot_tilt>0), color=C['tilt'], alpha=.15, label='Eversion (+)')
ax1.fill_between(t, foot_tilt, where=(foot_tilt<0), color=C['noisy'], alpha=.15, label='Inversion (−)')
ax1.axhline(0, color='white', lw=.7, ls=':')
ax1.axhline( FOOT_TILT_MAX, color=C['high'],   lw=1.0, ls='--', label=f'HIGH limit ±{FOOT_TILT_MAX}°')
ax1.axhline(-FOOT_TILT_MAX, color=C['high'],   lw=1.0, ls='--')
ax1.axhline( FOOT_TILT_MED, color=C['medium'], lw=0.8, ls=':', label=f'MED limit ±{FOOT_TILT_MED}°')
ax1.axhline(-FOOT_TILT_MED, color=C['medium'], lw=0.8, ls=':')
_ax(ax1, 'Foot Tilt Angle', yl='Tilt [°]'); _leg(ax1)

# Tilt derivative (rate of inversion change)
tilt_d = np.gradient(foot_tilt, dt)
ax2.plot(t, tilt_d, color=C['noisy'], lw=1.4, alpha=.85, label='Tilt rate [°/s]')
ax2.axhline(0, color='white', lw=.6, ls=':')
_ax(ax2, 'Foot Tilt Rate of Change', xl='Time [s]', yl='d(tilt)/dt [°/s]'); _leg(ax2)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 12 — Full Joint Chain: Ankle / Knee / Hip
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 12] Full Joint Chain Angles …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 12 — V2: Full Joint Chain  Ankle → Knee → Hip\n'
             'Phase shifts show natural proximal-distal gait coupling',
             color='white', fontsize=12, fontweight='bold', y=.99)
chain = [(th_ankle,   th_ankle_d,   C['ankle'], 'Ankle Angle  [°]',    'Ankle'),
         (th_knee_v2, th_knee_v2_d, C['knee2'], 'Knee (V2) Angle  [°]','Knee (V2)'),
         (th_hip,     th_hip_d,     C['hip'],   'Hip Angle  [°]',       'Hip')]
for ax, (ang, vel, col, yl, label) in zip(axes, chain):
    ax.plot(t, ang, color=col,  lw=1.8, label=f'{label} angle')
    ax_v = ax.twinx()
    ax_v.plot(t, vel, color=col, lw=0.9, alpha=0.4, ls='--', label=f'{label} vel')
    ax_v.tick_params(colors='#888', labelsize=6)
    ax_v.set_ylabel('Vel [°/s]', color='#AAAAAA', fontsize=7)
    ax_v.spines['right'].set_edgecolor('#30363D')
    _ax(ax, f'{label} Joint', yl=yl)
    _leg(ax, loc='upper left')
axes[-1].set_xlabel('Time [s]', color='#AAAAAA', fontsize=8)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 13 — Force Components: Vertical vs Lateral
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 13] Force Components …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 13 — V2: Force Vector Components\n'
             'F_eff = m·g·cos(tilt)  |  F_lateral = m·g·sin(tilt)  |  '
             'F_joint = f(both, θ_knee)',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax = axes[0]
ax.plot(t, F_eff,     color=C['true'],    lw=1.6, label=f'F_eff = m·g·cos(tilt)')
ax.plot(t, F_lateral, color=C['lateral'], lw=1.4, alpha=.85, label='F_lateral = m·g·sin(tilt)')
ax.axhline(0, color='#444', lw=.7, ls=':')
_ax(ax, 'Effective vs Lateral Force', yl='Force [N]'); _leg(ax)
ax = axes[1]
ax.plot(t, F_total, color=C['pressure'], lw=1.8, label='Total joint load')
ax.fill_between(t, F_total,
                where=(F_total > F_total.mean()+2*F_total.std()),
                color=C['high'], alpha=.35, label='Peak load zone')
ax.axhline(F_total.mean(), color='white', lw=.8, ls='--', label='Mean load')
_ax(ax, 'Total Joint Load  √(F_eff² + F_lat²) · |sin θ_knee|', yl='Load [N]'); _leg(ax)
ax = axes[2]
ax.plot(t, foot_tilt, color=C['tilt'],   lw=1.4, label='Foot tilt [°]')
ax_r = ax.twinx()
ax_r.plot(t, F_lateral, color=C['lateral'], lw=1.2, alpha=.8, ls='--', label='F_lateral [N]')
ax_r.tick_params(colors='#888', labelsize=6)
ax_r.set_ylabel('F_lat [N]', color='#AAAAAA', fontsize=7)
ax_r.spines['right'].set_edgecolor('#30363D')
_ax(ax, 'Foot Tilt → Lateral Force Coupling', xl='Time [s]', yl='Tilt [°]')
_leg(ax, loc='upper left')
plt.tight_layout(rect=[0, 0, 1, .95]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 14 — sEMG Signal
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 14] sEMG Signal …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 14 — V2: Simulated sEMG Signal\n'
             'Activation envelope ∝ joint load × angular velocity',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax = axes[0]
ax.plot(t, activation, color=C['emg'], lw=1.6, label='Activation driver (0–1)')
ax.fill_between(t, activation, alpha=.15, color=C['emg'])
_ax(ax, 'Muscle Activation Driver', yl='Activation [a.u.]'); _leg(ax)
ax = axes[1]
ax.plot(t, emg_clean, color=C['true'],  lw=1.8, label='Clean EMG envelope')
ax.axhline(emg_spike_thr, color=C['high'], lw=1.0, ls='--', label=f'Spike threshold')
ax.fill_between(t, emg_clean,
                where=(emg_clean > emg_spike_thr),
                color=C['high'], alpha=.35, label='EMG spike')
_ax(ax, 'Clean sEMG Envelope', yl='EMG [mV norm]'); _leg(ax)
ax = axes[2]
ax.plot(t, emg_noisy, color=C['noisy'],  lw=.8, alpha=.6,  label='Noisy EMG (wireless artefact)')
ax.plot(t, emg_clean, color=C['kalman'], lw=1.6,            label='Clean envelope')
_ax(ax, 'Noisy vs Clean EMG', xl='Time [s]', yl='EMG [mV norm]'); _leg(ax)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 15 — EMG vs Force Correlation
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 15] EMG vs Force Correlation …")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 15 — V2: EMG vs Joint Force Correlation\n'
             'Validates that EMG activation tracks mechanical load',
             color='white', fontsize=12, fontweight='bold')
# Scatter: EMG vs total force
sc = ax1.scatter(F_total, emg_clean, c=t, cmap='plasma', s=3, alpha=.6)
cbar = plt.colorbar(sc, ax=ax1)
cbar.set_label('Time [s]', color='white', fontsize=8)
cbar.ax.yaxis.set_tick_params(color='white')
plt.setp(plt.getp(cbar.ax.axes, 'yticklabels'), color='white', fontsize=7)
corr = np.corrcoef(F_total, emg_clean)[0, 1]
ax1.text(.05,.93,f'r = {corr:.3f}',transform=ax1.transAxes,
         color='#FFD93D',fontsize=11,fontweight='bold')
_ax(ax1,'EMG vs Total Joint Force',xl='F_joint [N]',yl='EMG [mV norm]')
# Time series overlay (normalised)
ax2.plot(t, F_total/F_total.max(),     color=C['pressure'], lw=1.6, label='F_joint (norm)')
ax2.plot(t, emg_clean/emg_clean.max(), color=C['emg'],      lw=1.4, alpha=.85, label='EMG (norm)')
_ax(ax2,'Force & EMG Over Time (normalised)',xl='Time [s]',yl='Normalised [0–1]'); _leg(ax2)
plt.tight_layout(rect=[0, 0, 1, .93]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 16 — Sensor Fusion Output
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 16] Sensor Fusion …")
fig, axes = plt.subplots(2, 1, figsize=(14, 8), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle(f'VIZ 16 — V2: Multi-Modal Sensor Fusion\n'
             f'Joint Load Estimate = {W1}·|angle_norm| + {W2}·|vel_norm| + {W3}·EMG_norm',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax = axes[0]
ax.plot(t, ang_norm_v2, color=C['knee2'],  lw=1.2, label=f'Angle ({W1})')
ax.plot(t, vel_norm_v2, color=C['vel'],    lw=1.2, label=f'Velocity ({W2})')
ax.plot(t, emg_norm,    color=C['emg'],    lw=1.2, label=f'EMG ({W3})')
_ax(ax, 'Individual Sensor Components (normalised)', yl='Value [0–1]'); _leg(ax)
ax = axes[1]
ax.plot(t, fusion_est, color=C['fusion'], lw=2.0, label='Fused joint load estimate')
ax.fill_between(t, fusion_est, alpha=.12, color=C['fusion'])
ax.axhline(fusion_est.mean(), color='white', lw=.8, ls='--',
           label=f'Mean = {fusion_est.mean():.3f}')
ax.fill_between(t, fusion_est,
                where=(fusion_est > fusion_est.mean()+2*fusion_est.std()),
                color=C['high'], alpha=.35, label='High load zone')
_ax(ax,'Fused Estimate',xl='Time [s]',yl='Load estimate [0–1]'); _leg(ax)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 17 — V2 Risk Detection
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 17] V2 Risk Detection …")
fig, axes = plt.subplots(4, 1, figsize=(14, 12), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 17 — V2: Multi-Modal Risk Detection\n'
             'Foot tilt + EMG spikes + force peaks + velocity — all flagged together',
             color='white', fontsize=12, fontweight='bold', y=.99)
ax = axes[0]
ax.plot(t, foot_tilt, color=C['tilt'], lw=1.6)
ax.fill_between(t, foot_tilt, where=hi_v2, color=C['high'],   alpha=.35, label='HIGH')
ax.fill_between(t, foot_tilt, where=me_v2, color=C['medium'], alpha=.30, label='MED')
ax.axhline( FOOT_TILT_MAX, color=C['high'],   lw=1.0, ls='--', label=f'HIGH limit')
ax.axhline(-FOOT_TILT_MAX, color=C['high'],   lw=1.0, ls='--')
_ax(ax,'Foot Tilt — Risk Zones',yl='Tilt [°]'); _leg(ax)
ax = axes[1]
ax.plot(t, emg_clean, color=C['emg'], lw=1.4)
ax.fill_between(t, emg_clean,
                where=(emg_clean>emg_spike_thr),
                color=C['high'], alpha=.4, label='EMG spike (HIGH)')
ax.axhline(emg_spike_thr, color=C['high'], lw=1.0, ls='--', label=f'Spike threshold')
_ax(ax,'EMG — Spike Detection',yl='EMG [mV norm]'); _leg(ax)
ax = axes[2]
ax.plot(t, F_total, color=C['pressure'], lw=1.4)
ax.fill_between(t, F_total, where=hi_v2, color=C['high'],   alpha=.35, label='HIGH load')
ax.fill_between(t, F_total, where=me_v2, color=C['medium'], alpha=.30, label='MED load')
ax.axhline(load_thr, color=C['high'], lw=1.0, ls='--', label='Load threshold')
_ax(ax,'Joint Force — Risk Zones',yl='F_joint [N]'); _leg(ax)
ax = axes[3]
ax.scatter(t, fusion_est, c=rc_v2, s=4, linewidths=0, zorder=3)
for lbl,col in [('HIGH',C['high']),('MEDIUM',C['medium']),('LOW',C['low'])]:
    ax.scatter([],[],color=col,s=20,label=lbl)
_ax(ax,'Fusion Estimate — Risk Classification',xl='Time [s]',yl='Load est [0–1]'); _leg(ax)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 18 — Clean vs Noisy EMG Comparison
# ══════════════════════════════════════════════════════════════════════════════
print("  [VIZ 18] Clean vs Noisy EMG …")
fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
fig.patch.set_facecolor(C['panel'])
fig.suptitle('VIZ 18 — V2: Clean vs Noisy EMG  +  Kalman-Filtered Recovery\n'
             'Gaussian artefact from wireless transmission modelled explicitly',
             color='white', fontsize=12, fontweight='bold', y=.99)
# Kalman-filter the noisy EMG
emg_kal = kalman(emg_noisy, Q=0.001, R=0.01)
rn_emg  = np.sqrt(np.mean((emg_noisy-emg_clean)**2))
rk_emg  = np.sqrt(np.mean((emg_kal  -emg_clean)**2))
ax = axes[0]
ax.plot(t, emg_clean, color=C['true'],  lw=1.8, label='Clean EMG')
_ax(ax,'Clean EMG Envelope (ground truth)',yl='EMG [mV norm]'); _leg(ax)
ax = axes[1]
ax.plot(t, emg_noisy, color=C['noisy'],  lw=.8, alpha=.65, label=f'Noisy EMG  RMSE={rn_emg:.4f}')
ax.plot(t, emg_clean, color=C['true'],   lw=1.6,            label='Clean EMG')
_ax(ax,'Noisy EMG (wireless artefact)',yl='EMG [mV norm]'); _leg(ax)
ax = axes[2]
ax.plot(t, emg_noisy, color=C['noisy'],  lw=.7, alpha=.5,  label=f'Noisy RMSE={rn_emg:.4f}')
ax.plot(t, emg_clean, color=C['true'],   lw=1.5,            label='Clean EMG')
ax.plot(t, emg_kal,   color=C['kalman'], lw=1.6, ls='--',   label=f'Kalman RMSE={rk_emg:.4f}')
_ax(ax,f'Kalman Recovery  ({100*(1-rk_emg/rn_emg):.1f}% improvement)',
    xl='Time [s]', yl='EMG [mV norm]'); _leg(ax)
plt.tight_layout(rect=[0, 0, 1, .96]); show(fig)

# ══════════════════════════════════════════════════════════════════════════════
#  GIF 2 — Full-Chain Animation  (hip → knee → ankle + foot tilt)
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [GIF 2] Rendering full-chain animation (60 frames) …")

def full_chain_frame(ax, ang_hip, ang_knee, ang_ankle, tilt, rc):
    """
    Draw a 4-segment leg: hip → thigh → knee → shin → ankle → foot.
    All angles measured from vertical.  Tilt rotates the foot segment.
    """
    ax.set_facecolor(C['bg'])
    ax.set_xlim(-2.0, 2.0); ax.set_ylim(-4.0, 0.6)
    ax.set_aspect('equal'); ax.axis('off')

    L = 1.0  # normalised segment length
    # Hip (origin at top)
    hx, hy = 0.0, 0.0
    # Thigh — angled by hip
    r_hip  = np.deg2rad(ang_hip)
    kx = hx + L*np.sin(r_hip); ky = hy - L*np.cos(r_hip)
    # Shin — angled by knee (relative to thigh direction)
    r_knee = np.deg2rad(ang_knee)
    sx = kx + L*np.sin(r_hip + r_knee); sy = ky - L*np.cos(r_hip + r_knee)
    # Foot — angled by ankle + tilt
    r_ankle = np.deg2rad(ang_ankle + tilt*0.3)
    fx = sx + 0.6*np.sin(r_hip+r_knee+r_ankle)
    fy = sy - 0.6*np.cos(r_hip+r_knee+r_ankle)

    # Draw segments
    segs = [([hx,kx],[hy,ky],C['hip'],  10,'Thigh'),
            ([kx,sx],[ky,sy],rc,          10,'Shin'),
            ([sx,fx],[sy,fy],C['ankle'],   8,'Foot')]
    for xs, ys, col, lw, lbl in segs:
        ax.plot(xs, ys, color=col, lw=lw, solid_capstyle='round', zorder=2)

    # Joints
    ax.scatter([hx,kx,sx,fx],[hy,ky,sy,fy],
               color='white', s=80, zorder=5)

    # Ground
    ax.axhline(fy, color='#444', lw=1.2, ls='--', alpha=.6)

    # Labels
    ax.text(0, 0.45, f'Hip {ang_hip:.1f}°',
            ha='center', color=C['hip'],   fontsize=8, fontweight='bold')
    ax.text(kx+.15, ky+.1, f'Knee {ang_knee:.1f}°',
            ha='left',   color=rc,          fontsize=8, fontweight='bold')
    ax.text(sx+.12, sy,    f'Ankle {ang_ankle:.1f}°',
            ha='left',   color=C['ankle'],  fontsize=8, fontweight='bold')
    ax.text(0, fy-.25, f'Tilt {tilt:.1f}°',
            ha='center', color=C['tilt'],   fontsize=8)

gif2_frames = []
frame_idx2  = np.linspace(0, int(2*T_c/(t[1]-t[0])), 60, dtype=int)
frame_idx2  = np.clip(frame_idx2, 0, len(t)-1)

for fi, di in enumerate(frame_idx2):
    fig = plt.figure(figsize=(13, 5))
    fig.patch.set_facecolor(C['panel'])

    # Left: full chain anatomy
    ax_chain = fig.add_axes([0.02, 0.04, 0.30, 0.90])
    rc_now   = C['high'] if hi_v2[di] else C['medium'] if me_v2[di] else C['low']
    rlvl     = 'HIGH'    if hi_v2[di] else 'MEDIUM'    if me_v2[di] else 'LOW'
    full_chain_frame(ax_chain,
                     th_hip[di], th_knee_v2[di], th_ankle[di],
                     foot_tilt[di], rc_now)
    ax_chain.set_title('Full Joint Chain', color='white',
                       fontsize=10, fontweight='bold', pad=4)

    x_lim2 = t[int(2*T_c/(t[1]-t[0]))]

    # Top-right: joint angles
    ax_a = fig.add_axes([0.36, 0.55, 0.60, 0.37])
    ax_a.set_facecolor(C['bg'])
    ax_a.plot(t[:di+1], th_hip[:di+1],       color=C['hip'],  lw=1.4, label='Hip')
    ax_a.plot(t[:di+1], th_knee_v2[:di+1],   color=rc_now,    lw=1.4, label='Knee')
    ax_a.plot(t[:di+1], th_ankle[:di+1],     color=C['ankle'],lw=1.4, label='Ankle')
    ax_a.plot(t[:di+1], foot_tilt[:di+1],    color=C['tilt'], lw=1.0, ls='--', label='Tilt')
    ax_a.axvline(t[di], color='white', lw=.7, alpha=.5)
    ax_a.set_xlim(0, x_lim2)
    ax_a.set_ylabel('Angle [°]', color='#AAAAAA', fontsize=8)
    ax_a.tick_params(colors='#888', labelsize=7)
    for s in ax_a.spines.values(): s.set_edgecolor('#30363D')
    ax_a.grid(color='#21262D', lw=.5, ls='--', alpha=.7)
    ax_a.legend(fontsize=7, facecolor='#21262D', edgecolor='#444',
                labelcolor='white', ncol=4, loc='upper left')
    ax_a.set_title('Joint Angles', color='white', fontsize=9, fontweight='bold', pad=4)

    # Bottom-right: EMG + force
    ax_ef  = fig.add_axes([0.36, 0.08, 0.60, 0.37])
    ax_ef2 = ax_ef.twinx()
    ax_ef.set_facecolor(C['bg'])
    ax_ef.plot(t[:di+1], emg_clean[:di+1],
               color=C['emg'],      lw=1.4, label='EMG [mV norm]')
    ax_ef2.plot(t[:di+1], F_total[:di+1],
                color=C['pressure'], lw=1.0, alpha=.8, ls='--', label='F_joint [N]')
    ax_ef.axvline(t[di], color='white', lw=.7, alpha=.5)
    ax_ef.scatter([t[di]],[emg_clean[di]], color=C['emg'],  s=45, zorder=5)
    ax_ef2.scatter([t[di]],[F_total[di]],  color=C['pressure'],s=45,zorder=5)
    ax_ef.set_xlim(0, x_lim2)
    ax_ef.set_xlabel('Time [s]', color='#AAAAAA', fontsize=8)
    ax_ef.set_ylabel('EMG [mV]', color='#AAAAAA', fontsize=8)
    ax_ef2.set_ylabel('Force [N]', color='#AAAAAA', fontsize=8)
    for ax_ in [ax_ef, ax_ef2]:
        ax_.tick_params(colors='#888', labelsize=7)
        for s in ax_.spines.values(): s.set_edgecolor('#30363D')
    ax_ef.grid(color='#21262D', lw=.5, ls='--', alpha=.7)
    h1,l1=ax_ef.get_legend_handles_labels()
    h2,l2=ax_ef2.get_legend_handles_labels()
    ax_ef.legend(h1+h2,l1+l2,fontsize=7,facecolor='#21262D',
                 edgecolor='#444',labelcolor='white',loc='upper left')
    ax_ef.set_title('EMG & Joint Force', color='white',
                    fontsize=9, fontweight='bold', pad=4)

    # Risk badge
    fig.text(.5, .98,
             f'V2 Digital Twin  |  Foot tilt={foot_tilt[di]:.1f}°  |  '
             f'Risk: {rlvl}  |  Earth g=9.81 m/s²',
             ha='center', va='top', color=rc_now,
             fontsize=10, fontweight='bold')

    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=100, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    buf.seek(0)
    gif2_frames.append(PILImage.open(buf).copy().convert('RGB'))
    plt.close(fig)
    if (fi+1) % 15 == 0:
        print(f"    {fi+1}/{len(frame_idx2)} frames")

gif2 = 'biomech_simulation.gif'
gif2_frames[0].save(gif2, save_all=True, append_images=gif2_frames[1:],
                    duration=80, loop=0, optimize=False)
print(f"  ✓ GIF 2 saved → {gif2}  ({os.path.getsize(gif2)/1e6:.1f} MB)")
display(IPImage(filename=gif2))

# ══════════════════════════════════════════════════════════════════════════════
#  VIZ 19 — V2 Interactive Slider  (foot tilt + body weight + gravity)
# ══════════════════════════════════════════════════════════════════════════════
print("\n  [VIZ 19] V2 Interactive Slider — foot tilt / weight / gravity …\n")

def _v2_update(foot_tilt_deg=0, body_weight=70, environment='Earth'):
    g   = GRAVITY[environment]
    ft  = np.deg2rad(foot_tilt_deg)
    # Compute derived values
    F_e = body_weight * g * np.cos(ft)           # effective vertical
    F_l = body_weight * g * np.sin(ft)           # lateral
    # Example knee at 30° flex
    knee_ex  = 30.0
    F_j = np.sqrt(F_e**2 + F_l**2) * abs(np.sin(np.deg2rad(knee_ex)))
    # Approx EMG activation from force
    emg_val = min(F_j / (body_weight * g + 1e-6), 1.0)
    # Risk
    risk_v2 = ('HIGH'   if abs(foot_tilt_deg) > FOOT_TILT_MAX or F_j > 200 else
               'MEDIUM' if abs(foot_tilt_deg) > FOOT_TILT_MED or F_j > 100 else 'LOW')
    rc2 = C['high'] if risk_v2=='HIGH' else C['medium'] if risk_v2=='MEDIUM' else C['low']

    fig, axes = plt.subplots(1, 4, figsize=(20, 5))
    fig.patch.set_facecolor(C['panel'])
    fig.suptitle(
        f'VIZ 19 — V2 Interactive  |  Tilt={foot_tilt_deg}°  |  '
        f'Weight={body_weight} kg  |  {environment} (g={g} m/s²)  |  '
        f'Risk: {risk_v2}',
        color=rc2, fontsize=11, fontweight='bold')

    # Panel 1: full-chain anatomy snapshot
    ax = axes[0]; ax.set_facecolor(C['bg'])
    ax.set_xlim(-2.0,2.0); ax.set_ylim(-3.8,0.6)
    ax.set_aspect('equal'); ax.axis('off')
    full_chain_frame(ax, ang_hip=10.0, ang_knee=knee_ex,
                     ang_ankle=5.0+foot_tilt_deg*0.3,
                     tilt=foot_tilt_deg, rc=rc2)
    ax.set_title('Joint Chain', color='white', fontsize=9, fontweight='bold', pad=4)

    # Panel 2: foot tilt dial (bar)
    ax2 = axes[1]; ax2.set_facecolor(C['bg'])
    tilt_col = C['noisy'] if foot_tilt_deg < 0 else C['tilt']
    ax2.barh(['Foot Tilt [°]'], [abs(foot_tilt_deg)], color=tilt_col,
             height=.4, edgecolor='#30363D', lw=.5)
    ax2.set_xlim(0, 35)
    direction = 'Inversion' if foot_tilt_deg < 0 else 'Eversion'
    ax2.text(abs(foot_tilt_deg)+0.5, 0,
             f'{abs(foot_tilt_deg)}°  ({direction})',
             va='center', color='white', fontsize=10, fontweight='bold')
    _ax(ax2,'Foot Tilt')

    # Panel 3: force components bar
    ax3 = axes[2]; ax3.set_facecolor(C['bg'])
    cats3  = ['F_eff [N]','F_lateral [N]','F_joint [N]']
    vals3  = [F_e, abs(F_l), F_j]
    bcols3 = [C['true'], C['lateral'], rc2]
    bs3 = ax3.barh(cats3, vals3, color=bcols3, height=.4,
                   edgecolor='#30363D', lw=.5)
    ax3.set_xlim(0, max(vals3)*1.35+10)
    for b,v in zip(bs3,vals3):
        ax3.text(b.get_width()+2, b.get_y()+b.get_height()/2,
                 f'{v:.1f}', va='center', color='white',
                 fontsize=9, fontweight='bold')
    _ax(ax3,'Force Components')

    # Panel 4: gravity pressure comparison
    ax4 = axes[3]; ax4.set_facecolor(C['bg'])
    envl   = ['Earth','Moon','Mars']
    F_all  = [body_weight*GRAVITY[e]*np.cos(ft)*abs(np.sin(np.deg2rad(knee_ex)))
              for e in envl]
    bb = ax4.bar(envl, F_all,
                 color=[C['earth'],C['moon'],C['mars']],
                 width=.5, edgecolor='#30363D', lw=.5)
    for b,v in zip(bb,F_all):
        ax4.text(b.get_x()+b.get_width()/2, b.get_height()+0.5,
                 f'{v:.1f}', ha='center', color='white',
                 fontsize=9, fontweight='bold')
    bb[envl.index(environment)].set_edgecolor('white')
    bb[envl.index(environment)].set_linewidth(2.5)
    _ax(ax4,f'F_joint by Environment\n(knee={knee_ex}°)',yl='Force [N]')
    ax4.tick_params(axis='x',colors='#AAAAAA',labelsize=9)

    # EMG readout as text overlay
    fig.text(.5,.01,
             f'EMG activation ≈ {emg_val:.2f}  |  '
             f'F_effective={F_e:.1f} N  F_lateral={abs(F_l):.1f} N  F_joint={F_j:.1f} N',
             ha='center', color='#AAAAAA', fontsize=9)

    plt.tight_layout(rect=[0,0,1,.88]); show(fig)

tilt_w   = widgets.IntSlider(value=0, min=-30, max=30, step=1,
                              description='Foot tilt °:',
                              style={'description_width':'80px'},
                              layout=widgets.Layout(width='350px'))
weight_w = widgets.IntSlider(value=70, min=40, max=120, step=5,
                              description='Weight kg:',
                              style={'description_width':'80px'},
                              layout=widgets.Layout(width='300px'))
grav_w   = widgets.Dropdown(options=['Earth','Moon','Mars'], value='Earth',
                             description='Gravity:',
                             style={'description_width':'60px'},
                             layout=widgets.Layout(width='190px'))
display(widgets.HBox([tilt_w, weight_w, grav_w]),
        widgets.interactive_output(_v2_update,
                                   {'foot_tilt_deg': tilt_w,
                                    'body_weight':   weight_w,
                                    'environment':   grav_w}))

# ══════════════════════════════════════════════════════════════════════════════
#  SUMMARY
# ══════════════════════════════════════════════════════════════════════════════
print("\n" + "━"*65)
print("  ALL OUTPUTS COMPLETE — scroll up to review in order:")
print()
print("  ── V1 (unchanged) ──────────────────────────────────────")
print("  VIZ 1   Gait motion  (angle / velocity / acceleration)")
print("  VIZ 2   Sensor simulation  Earth / Moon / Mars")
print("  VIZ 3   Noise injection on all sensor channels")
print("  VIZ 4   Kalman filter  true vs noisy vs estimated")
print("  VIZ 5   Feature extraction bar chart")
print("  VIZ 6   Risk dashboard  (3 channels, risk-shaded)")
print("  VIZ 7   Knee anatomy snapshots across one gait cycle")
print("  VIZ 8   Gravity pressure profile comparison")
print("  VIZ 9   Master 4×2 dashboard  (all V1 phases)")
print("  GIF 1   knee_motion_animation.gif  (knee + real-time graphs)")
print("  VIZ 10  V1 Interactive slider  (angle + gravity)")
print()
print("  ── V2 (new extensions) ──────────────────────────────────")
print("  VIZ 11  Foot tilt vs time  (inversion / eversion)")
print("  VIZ 12  Full joint chain  ankle → knee → hip angles")
print("  VIZ 13  Force components  vertical vs lateral")
print("  VIZ 14  sEMG signal  (activation + clean + noisy)")
print("  VIZ 15  EMG vs force correlation  (scatter + time series)")
print("  VIZ 16  Sensor fusion output  (IMU + fiber + EMG)")
print("  VIZ 17  V2 risk detection  (4 channels)")
print("  VIZ 18  Clean vs noisy EMG  + Kalman recovery")
print("  GIF 2   biomech_simulation.gif  (full chain animation)")
print("  VIZ 19  V2 Interactive slider  (tilt + weight + gravity)")
print("━"*65)